### ISSUE TITLE
Excessive build time

### ISSUE THREAD

**Issue by awoods** [cavendish-ldp/cavendish#13]
Feel free to close this issue if you would like after reading it, but I wanted to note that it took slightly over an hour to run `mvn clean install` on the `cavendish` project.
```
[INFO] Reactor Summary:
[INFO] 
[INFO] cavendish .......................................... SUCCESS [  0.140 s]
[INFO] cavendish-ldp ...................................... SUCCESS [  3.165 s]
[INFO] cavendish-blazegraph ............................... SUCCESS [  2.304 s]
[INFO] cavendish-jetty .................................... SUCCESS [  01:17 h]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:17 h
[INFO] Finished at: 2017-02-13T17:06:53-05:00
[INFO] Final Memory: 36M/466M
[INFO] ------------------------------------------------------------------------
```
Is this expected?

**Comment by barmintor** [comment]
No, and I'm having a little trouble reproducing it locally. Maybe there's an unexpected BlazeGraph configuration getting picked up on your machine?

**Comment by awoods** [comment]
After further investigation, the issue on my Ubuntu 17.04 is coming from:
https://github.com/cavendish-ldp/cavendish/blob/master/cavendish-jetty/src/main/java/cavendish/jetty/handler/LdpHandler.java#L861
...Cavendish blocks at that line per the comment in the JavaDocs for the [SecureRandom](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) class:
```
Note: Depending on the implementation, the generateSeed and nextBytes methods may block as entropy is being gathered, for example, if they need to read from /dev/random on various Unix-like operating systems.
```

As an interim fix, replacing the existing `try` block with the following works:
```
return Long.toUnsignedString(new Random().nextLong());
```
However, we will likely want to have a more robust UUID approach ;)

**Comment by awoods** [comment]
Addressed by: https://github.com/cavendish-ldp/cavendish/pull/21
